"""Sample fixture data for dummy API endpoints.

This module now exposes a single `DATA` list where each record has a `kind`
field ("closure" or "blockage"). `CLOSURE_DATA` and `BLOCKAGE_DATA` are
derived for backward-compatibility.
"""

DATA = [
    {#$$
        "kind": "blockage",
        "Assessor": "TECHM",
        "Contractor": "mjq",
        "Contractor AFP ref": "AFP1214",
        "Purchase Order ID": "PO-020062",
        "Region": "Wales",
        "Town": "NEATH ATE",
        "Polygon Type": "GF",
        "Polygon ID": 167354,
        "Feature ID": 121396,
        "Build Status": 7,
        "code": "H&D125",
        "item": "96.5mm uPVC DUCT REPAIR KIT",
        "unit": "ITEMS",
        "price": 200.00,
        "quantity": 1,
        "total": 200.00,
    },
    {#
    "kind": "closure",
    "Assessor": "TECHM",
    "Contractor AFP ref": "DRAFT",
    "Purchase Order ID": "PO-021605",
    "Region": "Wales",
    "Town": "CARDIFF",
    "Polygon Type": "FN",
    "Polygon ID": 248567,
    "Feature ID": 340255,
    "Build Status": 7,
    "code": "TST003",
    "item": "Test Equipment Type 3",
    "unit": "Per Test",
    "price": 85.00,
    "quantity": 1,
    "total": 85.00,
    },
    {#
        "kind": "closure",
        "Assessor": "TECHM",
        "Contractor AFP ref": "DRAFT",
        "Purchase Order ID": "PO-021603",
        "Region": "South West",
        "Town": "EXETER",
        "Polygon Type": "FN",
        "Polygon ID": 248565,
        "Feature ID": 337217,
        "Build Status": 7,
        "code": "TST003",
        "item": "Test Equipment Type 3",
        "unit": "Per Test",
        "price": 85.00,
        "quantity": 1,
        "total": 85.00,
    },
    {#$$
        "kind": "blockage",
        "Assessor": "TECHM",
        "Contractor": "mjq",
        "Contractor AFP ref": "AFP1215",
        "Purchase Order ID": "PO-020063",
        "Region": "Wales",
        "Town": "SWANSEA",
        "Polygon Type": "GF",
        "Polygon ID": 167355,
        "Feature ID": 121398,
        "Build Status": 7,
        "code": "BLK001",
        "item": "Blockage Clearance",
        "unit": "ITEMS",
        "price": 150.00,
        "quantity": 1,
        "total": 150.00,
    },

    {#
        "kind": "blockage",
        "Assessor": "TECHM",
        "Contractor": "ghi",
        "Contractor AFP ref": "AFP1219",
        "Purchase Order ID": "PO-020067",
        "Region": "South West",
        "Town": "PLYMOUTH",
        "Polygon Type": "GF",
        "Polygon ID": 167358,
        "Feature ID": 337226,
        "Build Status": 7,
        "code": "H&D147",
        "item": "150mm uPVC DUCT REPAIR KIT",
        "unit": "ITEMS",
        "price": 280.00,
        "quantity": 1,
        "total": 280.00,
},
]

CLOSURE_DATA = [item for item in DATA if item.get("kind") == "closure"]
BLOCKAGE_DATA = [item for item in DATA if item.get("kind") == "blockage"]
all = ["DATA", "CLOSURE_DATA", "BLOCKAGE_DATA"]